// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLMidGuLkK1o5N-gTb0aIrqwQD0yI8Q8U',
    appId: '1:986200647692:web:050ffc7b5d82d86355e629',
    messagingSenderId: '986200647692',
    projectId: 'pageflipper3',
    authDomain: 'pageflipper3.firebaseapp.com',
    storageBucket: 'pageflipper3.appspot.com',
    measurementId: 'G-2M09WC4PBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOjlQtsQq9B-uklHyAnHZtQ36Xyx-EkRs',
    appId: '1:986200647692:android:d7fa4fa2a48acf3555e629',
    messagingSenderId: '986200647692',
    projectId: 'pageflipper3',
    storageBucket: 'pageflipper3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAerO4DDxWkC4sG5PyuApGNY_fJjMBdjYk',
    appId: '1:986200647692:ios:e02c22a96794890455e629',
    messagingSenderId: '986200647692',
    projectId: 'pageflipper3',
    storageBucket: 'pageflipper3.appspot.com',
    iosBundleId: 'com.example.pageflipper3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAerO4DDxWkC4sG5PyuApGNY_fJjMBdjYk',
    appId: '1:986200647692:ios:e02c22a96794890455e629',
    messagingSenderId: '986200647692',
    projectId: 'pageflipper3',
    storageBucket: 'pageflipper3.appspot.com',
    iosBundleId: 'com.example.pageflipper3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLMidGuLkK1o5N-gTb0aIrqwQD0yI8Q8U',
    appId: '1:986200647692:web:22671632aade9b7f55e629',
    messagingSenderId: '986200647692',
    projectId: 'pageflipper3',
    authDomain: 'pageflipper3.firebaseapp.com',
    storageBucket: 'pageflipper3.appspot.com',
    measurementId: 'G-0DVP0C927M',
  );
}